def fmt_obj(o): ...
def fmt_error_type(data_type, wrap_error_in: str = ""): ...
def fmt_type_name(data_type): ...
def fmt_type(data_type): ...
def fmt_jsdoc_union(type_strings): ...
def fmt_func(name, version): ...
def fmt_url(namespace_name, route_name, route_version): ...
def fmt_var(name): ...
def check_route_name_conflict(namespace) -> None: ...
