from _typeshed import Incomplete

def fmt_obj(o): ...
def fmt_camel(name, upper_first: bool = False, reserved: bool = True): ...
def fmt_enum_name(field_name, union): ...
def fmt_camel_upper(name, reserved: bool = True): ...
def fmt_public_name(name): ...
def fmt_class(name): ...
def fmt_class_caps(name): ...
def fmt_class_type(data_type, suppress_ptr: bool = False): ...
def fmt_func(name): ...
def fmt_type(data_type, tag: bool = False, has_default: bool = False, no_ptr: bool = False, is_prop: bool = False): ...
def fmt_route_type(data_type, tag: bool = False, has_default: bool = False): ...
def fmt_class_prefix(data_type): ...
def fmt_validator(data_type): ...
def fmt_serial_obj(data_type): ...
def fmt_serial_class(class_name): ...
def fmt_route_obj_class(namespace_name): ...
def fmt_routes_class(namespace_name, auth_type): ...
def fmt_route_var(namespace_name, route): ...
def fmt_route_func(route): ...
def fmt_func_args(arg_str_pairs): ...
def fmt_func_args_declaration(arg_str_pairs): ...
def fmt_func_args_from_fields(args): ...
def fmt_func_call(caller, callee, args: Incomplete | None = None): ...
def fmt_alloc_call(caller): ...
def fmt_default_value(field): ...
def fmt_ns_number_call(data_type): ...
def fmt_signature(func, args, return_type: str = "void", class_func: bool = False): ...
def is_primitive_type(data_type): ...
def fmt_var(name): ...
def fmt_property(field): ...
def fmt_import(header_file): ...
def fmt_property_str(prop, typ, attrs: Incomplete | None = None): ...
def append_to_jazzy_category_dict(jazzy_dict, label, item) -> None: ...
