def fmt_obj(o): ...
def fmt_class(name): ...
def fmt_func(name, version): ...
def fmt_type(data_type): ...
def fmt_var(name): ...
def fmt_default_value(namespace, field): ...
def check_route_name_conflict(namespace) -> None: ...
